Algoritmo "crescente"

Var
   x, Y : inteiro

Inicio

      escreval("Digite dois numeros: ")
      leia(x)
      leia(y)

      enquanto x <> y faca
      se x < Y entao
      escreval("CRESCENTE")
      senao
           se x > Y entao
           escreval("DECRESCENTE")
           fimse
      fimse
      escreval("Digite outro numeros: ")
      leia(x)
      leia(y)
      fimenquanto


Fimalgoritmo