Algoritmo "media_ponderada"

Var
     N, i : inteiro
     y, x, w, media : real


Inicio

      escreva("Quantos casos voce vai digitar? ")
      leia(N)
      
      para i de 1 ate N faca

      escreval("Digite tres numeros: ")
      leia(y)
      leia(x)
      leia(w)

      media <- ((Y * 2) + (x * 3) + (w * 5)) / 10
      
      escreval("MEDIA = ", media:3:1)
      fimpara




      
      

Fimalgoritmo